const actionTypes = {
  CREATE_INVOICE_START: 'CREATE_INVOICE_START',
  CREATE_INVOICE_SUCCESS: 'CREATE_INVOICE_SUCCESS',
  CREATE_INVOICE_FAIL: 'CREATE_INVOICE_FAIL',

  GET_INVOICES_START: 'GET_INVOICES_START',
  GET_INVOICES_SUCCESS: 'GET_INVOICES_SUCCESS',
  GET_INVOICES_FAIL: 'GET_INVOICES_FAIL',

  GET_INVOICE_START: 'GET_INVOICE_START',
  GET_INVOICE_SUCCESS: 'GET_INVOICE_SUCCESS',
  GET_INVOICE_FAIL: 'GET_INVOICE_FAIL',

  GET_ITEMS_START: 'GET_ITEMS_START',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_ITEMS_FAIL: 'GET_ITEMS_FAIL'
};

export default actionTypes;
