const actionTypes = {
  CREATE_INVOICE_SUCCESS: 'CREATE_INVOICE_SUCCESS',
  CREATE_INVOICE__FAIL: 'CREATE_INVOICE__FAIL',

  GET_INVOICE_SUCCESS: 'GET_INVOICE_SUCCESS',
  GET_INVOICE__FAIL: 'GET_INVOICE__FAIL'
};

export default actionTypes;
