const actionTypes = {
  CREATE_ITEM_START: 'CREATE_ITEM_START',
  CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
  CREATE_ITEM_FAIL: 'CREATE_ITEM_FAIL',

  GET_ITEMS_START: 'GET_ITEMS_START',
  GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
  GET_ITEMS_FAIL: 'GET_ITEMS_FAIL',

  GET_ITEM_START: 'GET_ITEM_START',
  GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
  GET_ITEM_FAIL: 'GET_ITEM_FAIL'
};

export default actionTypes;
